export { BaseForm } from './form'
export type { BaseFormParams, InputsParams } from './form'
export { BaseFormModal } from './modal'
export type { BaseFormModalParams } from './modal'
export { getFormValue } from './getData'
