export { Model } from './model.model'
export { Border } from './border.model'
export { Color } from './color.model'
export { Product } from './product.model'
export { Profile } from './profile.model'
export { Size } from './size.model'
export { Type } from './type.model'

export type { IModel } from './model.model'
export type { IBorder } from './border.model'
export type { IColor } from './color.model'
export type { IProfile } from './profile.model'
export type { IProduct } from './product.model'
export type { ISize } from './size.model'
export type { IType } from './type.model'
