export { EmployeePosition } from './employee-position.model'
export { Prom } from './prom.model'
export { Position } from './position.model'
export { Employee } from './employee.model'
export { Group } from './group.model'
export { Title } from './title.model'
export { School } from './school.model'

export type { IEmployeePosition } from './employee-position.model'
export type { IProm } from './prom.model'
export type { IPosition } from './position.model'
export type { IEmployee } from './employee.model'
export type { IGroup } from './group.model'
export type { ITitle } from './title.model'
export type { ISchool } from './school.model'
